### ISSUE TITLE
on running informer.py file

### ISSUE THREAD

**Issue by mmaithani** [zhouhaoyi/Informer2020#11]
`Use GPU: cuda:0
>>>>>>>start training : informer_ETTh1_ftM_sl96_ll48_pl24_dm512_nh8_el3_dl2_df1024_atprob_ebfixed_test_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 8521
val 2857
test 2857
Traceback (most recent call last):
  File "main_informer.py", line 69, in <module>
    exp.train(setting)
  File "/content/Informer2020/exp/exp_informer.py", line 157, in train
    outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/Informer2020/models/model.py", line 71, in forward
    dec_out = self.decoder(dec_out, enc_out, x_mask=dec_self_mask, cross_mask=dec_enc_mask)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/Informer2020/models/decoder.py", line 46, in forward
    x = layer(x, cross, x_mask=x_mask, cross_mask=cross_mask)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/Informer2020/models/decoder.py", line 23, in forward
    attn_mask=x_mask
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/Informer2020/models/attn.py", line 141, in forward
    attn_mask
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/Informer2020/models/attn.py", line 25, in forward
    attn_mask = TriangularCausalMask(B, L, device=queries.device)
  File "/content/Informer2020/utils/masking.py", line 7, in __init__
    self._mask = torch.triu(torch.ones(mask_shape, dtype=torch.bool), diagonal=1).to(device)
RuntimeError: "triu" not implemented for 'Bool'`

**Comment by mmaithani** [comment]
Use GPU: cuda:0
>>>>>>>start training : informer_ETTh1_ftM_sl96_ll48_pl24_dm512_nh8_el3_dl2_df1024_atprob_ebfixed_test_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 8521
val 2857
test 2857
Traceback (most recent call last):
  File "main_informer.py", line 69, in <module>
    exp.train(setting)
  File "/content/Informer2020/exp/exp_informer.py", line 157, in train
    outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/Informer2020/models/model.py", line 71, in forward
    dec_out = self.decoder(dec_out, enc_out, x_mask=dec_self_mask, cross_mask=dec_enc_mask)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/Informer2020/models/decoder.py", line 46, in forward
    x = layer(x, cross, x_mask=x_mask, cross_mask=cross_mask)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/Informer2020/models/decoder.py", line 23, in forward
    attn_mask=x_mask
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/Informer2020/models/attn.py", line 141, in forward
    attn_mask
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/Informer2020/models/attn.py", line 25, in forward
    attn_mask = TriangularCausalMask(B, L, device=queries.device)
  File "/content/Informer2020/utils/masking.py", line 7, in __init__
    self._mask = torch.triu(torch.ones(mask_shape, dtype=torch.bool), diagonal=1).to(device)
RuntimeError: "triu" not implemented for 'Bool'

**Comment by cookieminions** [comment]
Thanks for your issue. We have checked the dependency and updated the file `requirements.txt`. Now it should work correctly.

**Comment by mmaithani** [comment]
Thanks
