### ISSUE TITLE
Questions about the results

### ISSUE THREAD

**Issue by ZhangTP1996** [zhouhaoyi/Informer2020#134]
I download the codes and run the command you give:
python -u main_informer.py --model informer --data ETTh1 --attn prob --freq h
The data is downloaded from https://github.com/zhouhaoyi/ETDataset/tree/main/ETT-small

The result shows that the mse is 0.526 and mae is 0.510.

My questions are:
1. This result doesn't seem to match any of the results you give. Which experiment does this command reproduce?
2. Why is the test shape (2848, 24, 7) while the test size is 2857? What do the three numbers represent?

**Comment by ZhangTP1996** [comment]
> 1. Please refer to the commands under `/scripts/` for reproducing experimental results. If you use default arguments in `main_informer.py`, you will get the results of predicting length 24 and the results is in the upper left corner of Figure 5.
>    ![image](https://user-images.githubusercontent.com/18379035/117627243-8b9fe280-b1aa-11eb-8dba-51fdc74b4151.png)
> 2. The size of Train, Validation and Test data you see when running data is the size of dataloader. However, in code `exp/exp_informer.py` line 85-90, we used `drop_last=True`, so the dataloader will drop the last incomplete batch (it will not affect the test samples because we use the same batch_size for all methods and the test dataloader does not be shuffled). So the length of data is not the same with the length of dataloader when running the code.
> 
> https://github.com/zhouhaoyi/Informer2020/blob/e4cab482ab082765109eb99a4f1db3035d556b5c/exp/exp_informer.py#L76-L101

I run the command in the script as you suggest:
`python -u main_informer.py --model informer --data ETTh1 --features S --seq_len 720 --label_len 168 --pred_len 24 --e_layers 2 --d_layers 1 --attn prob --des 'Exp' --itr 5`

I guess this should reproduce the results of ETTh1 for univariate forecasting with predict length of 24.
However, I get the following results for 5 experiments:
mse:0.10226275026798248, mae:0.253961443901062
mse:0.17029963433742523, mae:0.34301695227622986
mse:0.11192743480205536, mae:0.2684330642223358
mse:0.13270115852355957, mae:0.29784220457077026
mse:0.16042234003543854, mae:0.33442461490631104

It is greatly different from the results "mse 0.098 mae 0.247" you give in the table. What happens?

**Comment by ZhangTP1996** [comment]
> Please refer to issue #102 , the parameters in `scripts/` are based on commit [99b59c1](https://github.com/zhouhaoyi/Informer2020/commit/99b59c181f871a1521a798a37287a27ba5b742a7) , you can roll back to commit [99b59c1](https://github.com/zhouhaoyi/Informer2020/commit/99b59c181f871a1521a798a37287a27ba5b742a7) to check out the experiment results by using the parameters in `scripts/`.

I use the version in commit 99b59c1 and run the same command and find this error:
`Traceback (most recent call last):
  File "main_informer.py", line 98, in <module>
    exp.train(setting)
  File "/home/covpreduser/Blob/ZTP/Informer2020-99b59c1/exp/exp_informer.py", line 246, in train
    self.model.load_state_dict(torch.load(best_model_path))
  File "/anaconda/lib/python3.8/site-packages/torch/serialization.py", line 592, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/anaconda/lib/python3.8/site-packages/torch/serialization.py", line 851, in _load
    result = unpickler.load()
  File "/anaconda/lib/python3.8/site-packages/torch/serialization.py", line 843, in persistent_load
    load_tensor(data_type, size, key, _maybe_decode_ascii(location))
  File "/anaconda/lib/python3.8/site-packages/torch/serialization.py", line 831, in load_tensor
    storage = zip_file.get_storage_from_record(name, size, dtype).storage()
RuntimeError: [enforce fail at inline_container.cc:145] . PytorchStreamReader failed reading file data/94764406644368: invalid header or archive is corrupted`
