### ISSUE TITLE
Error of tensor dimension

### ISSUE THREAD

**Issue by nassimaugsburg** [zhouhaoyi/Informer2020#14]
After executing the following command: 
**python -u main_informer.py --model informer --data ETTh1**  
 
with your downloaded data, I get the following error:
Use GPU: cuda:0
>>>>>>>start training : informer_ETTh1_ftM_sl96_ll48_pl24_dm512_nh8_el3_dl2_df1024_atprob_ebfixed_test_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 8521
val 2857
test 2857
Traceback (most recent call last):
  File "main_informer.py", line 69, in <module>
    exp.train(setting)
  File "C:\Users\User\Informer2020\exp\exp_informer.py", line 157, in train
    outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark)
  File "C:\Users\User\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\User\Informer2020\models\model.py", line 67, in forward
    enc_out = self.enc_embedding(x_enc, x_mark_enc)
  File "C:\Users\User\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\User\Informer2020\models\embed.py", line 95, in forward
    x = self.value_embedding(x) + self.position_embedding(x) + self.temporal_embedding(x_mark)
RuntimeError: The size of tensor a (98) must match the size of tensor b (96) at non-singleton dimension 1

**Comment by cookieminions** [comment]
Please check the version of pytorch, the way of padding in Conv1D has changed, so make sure pytorch==1.4.0

**Comment by nassimaugsburg** [comment]
Thank you for your reactivity.
