### ISSUE TITLE
您好，我在学习该模型的过程中修改时间频率为"w"之后，报了一个错误，是因为什么呢？

### ISSUE THREAD

**Issue by chenruhai** [zhouhaoyi/Informer2020#236]
报错如下：

`
imestamp('2008-06-29 00:00:00'), Timestamp('2008-06-30 00:00:00'), Timestamp('2008-07-01 00:00:
Traceback (most recent call last):
  File "main_informer.py", line 161, in <module>
    exp.train(setting)
  File "E:\Users\Administrator\Desktop\InformerTime\exp\exp_informer.py", line 194, in train
    train_data, train_loader = self._get_data(flag = 'train')
  File "E:\Users\Administrator\Desktop\InformerTime\exp\exp_informer.py", line 119, in _get_data
    cols=args.cols
  File "E:\Users\Administrator\Desktop\InformerTime\data\data_loader.py", line 226, in __init__
    self.__read_data__()
  File "E:\Users\Administrator\Desktop\InformerTime\data\data_loader.py", line 283, in __read_data__
    data_stamp = time_features(df_stamp, timeenc=self.timeenc, freq=self.freq)
  File "E:\Users\Administrator\Desktop\InformerTime\utils\timefeatures.py", line 155, in time_features
    return np.vstack([feat(dates) for feat in time_features_from_frequency_str(freq)]).transpose(1,0)
  File "E:\Users\Administrator\Desktop\InformerTime\utils\timefeatures.py", line 155, in <listcomp>
    return np.vstack([feat(dates) for feat in time_features_from_frequency_str(freq)]).transpose(1,0)
  File "E:\Users\Administrator\Desktop\InformerTime\utils\timefeatures.py", line 60, in __call__
    return (index.isocalendar().week - 1) / 52.0 - 0.5
AttributeError: 'DatetimeIndex' object has no attribute 'isocalendar'

`

**Comment by cookieminions** [comment]
1. 你可以检查pandas的版本
2. 可以将`utils/timefeatures.py`中使用WeekofYear的地方删除
