### ISSUE TITLE
本科小白求指点，如何用5个变量，1个结果变量来训练模型呢，c_out参数代表的是什么

### ISSUE THREAD

**Issue by waynewilll** [zhouhaoyi/Informer2020#300]
假设数据集一共六个变量，日期/变量一/变量二/变量三/变量四/变量五（就是结果），如何使用这样的数据集来进行训练和测试呢。
已尝试以下方法：将main_informe.py中的数据改成了【5，5，5】失败，改变了n_heads&enc_in&dec_in&c_out参数，均失败。
报错多为
Traceback (most recent call last):
  File "main_informer.py", line 104, in <module>
    exp.train(setting)
  File "C:\Users\wayne\reserach\Informer2020-main\exp\exp_informer.py", line 127, in train
    vali_data, vali_loader = self._get_data(flag = 'val')
  File "C:\Users\wayne\reserach\Informer2020-main\exp\exp_informer.py", line 95, in _get_data
    print(flag, len(data_set))
ValueError: __len__() should return >= 0

python -u main_informer.py --model informer --data BIT_data --attn prob

Traceback (most recent call last):
  File "main_informer.py", line 104, in <module>
    exp.train(setting)
  File "C:\Users\wayne\reserach\Informer2020-main\exp\exp_informer.py", line 126, in train
    train_data, train_loader = self._get_data(flag = 'train')
  File "C:\Users\wayne\reserach\Informer2020-main\exp\exp_informer.py", line 73, in _get_data
    Data = data_dict[self.args.data]
本科小白求各位大神指点

**Comment by waynewilll** [comment]
另外他的三种flag是啥意思啊，有大神能讲解一下吗

**Comment by wyz123341** [comment]
第一个报错是因为数据集长度太小 要把data_loader里面的12*30*24的24改成2

要5个变量预测1个变量就把MS改成【5,5,1】

**Comment by waynewilll** [comment]
另外请教一下EarlyStoping counter：3 out of 3是什么意思

**Comment by waynewilll** [comment]
另外这个训练好的模型存在哪里呀，我看results里面没有存到我训练的模型😢

**Comment by YLscnu** [comment]
> 另外这个训练好的模型存在哪里呀，我看results里面没有存到我训练的模型😢

在checkpoints里面找一下
