### ISSUE TITLE
freq修改会出现错误

### ISSUE THREAD

**Issue by rintoo** [zhouhaoyi/Informer2020#308]
换成周期级别的：args.freq = 'w'
会出现下述错误：
Traceback (most recent call last):
  File "D:/Informer2020-main/Informer2020-main/main_informer pycharm.py", line 131, in <module>
    exp.train(setting)
  File "D:\Informer2020-main\Informer2020-main\exp\exp_informer.py", line 152, in train
    for i, (batch_x,batch_y,batch_x_mark,batch_y_mark) in enumerate(train_loader):
  File "D:\coder\ANACONDA\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "D:\coder\ANACONDA\lib\site-packages\torch\utils\data\dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\coder\ANACONDA\lib\site-packages\torch\utils\data\_utils\fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "D:\coder\ANACONDA\lib\site-packages\torch\utils\data\_utils\collate.py", line 84, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "D:\coder\ANACONDA\lib\site-packages\torch\utils\data\_utils\collate.py", line 84, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "D:\coder\ANACONDA\lib\site-packages\torch\utils\data\_utils\collate.py", line 62, in default_collate
    raise TypeError(default_collate_err_msg_format.format(elem.dtype))
TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found object

原因是exp_informer.py中
`for i, (batch_x,batch_y,batch_x_mark,batch_y_mark) in enumerate(train_loader):`
无法对train_loader数据类型正确识别。因为数据在data_loader.py中
`data_stamp = time_features(df_stamp, timeenc=self.timeenc, freq=self.freq)`
产生了不正确的数据类型。
在time_features中offsets.Week: [DayOfMonth, WeekOfYear]给了一个正确的Float64Index和一个错误的Series
因此我的修改是WeekOfYear函数的返回：
` return pd.Float64Index((index.isocalendar().week - 1) / 52.0 - 0.5)`

我不确定其他的freq会不会也有类似的问题。但是目前使用week时需要注意一下

**Comment by zhouhaoyi** [comment]
这个已经修正，在最新的merge里面。#311
