### ISSUE TITLE
如何传入自己的数据，传入自己的数据报下面的错。

### ISSUE THREAD

**Issue by 1915982017** [zhouhaoyi/Informer2020#377]
Traceback (most recent call last):
  File "D:\pycharm_code\Informer2020\main_informer.py", line 105, in <module>
    exp.train(setting)
  File "D:\pycharm_code\Informer2020\exp\exp_informer.py", line 127, in train
    train_data, train_loader = self._get_data(flag = 'train')
  File "D:\pycharm_code\Informer2020\exp\exp_informer.py", line 74, in _get_data
    Data = data_dict[self.args.data]
KeyError: 'WT00153'

**Comment by Admim123** [comment]
是不是target没有替换成你自己数据集的列名啊

**Comment by TJiaR** [comment]
您好，您的问题成功解决了嘛，我也遇到了同样的问题，方便加q交流一下嘛，我的联系方式1432187256

**Comment by Cyue0316** [comment]
可能是需要在exp_informer.py的data_dict中添上自己的数据名称：如'my_data':Dataset_Custom,

**Comment by MountVoom** [comment]
可以参考一下其他类似issue如#405
